
services:
  - type: web
    name: cv-optimizer-pro
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cv-optimizer-db
          property: connectionString
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
    healthCheckPath: /
    disk:
      name: cv-optimizer-disk
      mountPath: /tmp
      sizeGB: 1

databases:
  - name: cv-optimizer-db
    databaseName: cv_optimizer
    user: cv_optimizer_user
    plan: starter
